### ISSUE TITLE
versions issue for RPI

### ISSUE THREAD

**Issue by ZalgoSoft** [gil9red/telegram__deep_dream_bot#1]
installed tensorflow by manual

https://linuxhint.com/install-tensorflow-raspberry-pi/

![изображение](https://user-images.githubusercontent.com/80800403/210133460-03c60fb8-4837-44e5-9158-208adc511b93.png)

**Comment by gil9red** [comment]
Hello!
An error in the name of the parameter in the function, because it matches the name of the operator

I have not supported the project for a long time. But I looked - I ran it on python 3.7, then, it seems, there was no async operator.

Try either using python 3.7 or update tensorflow to the latest version
